# Generated by Django 3.0.3 on 2020-03-03 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LodgingEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_id', models.PositiveIntegerField(verbose_name='ID Hospedaria')),
                ('host_name', models.CharField(max_length=50, verbose_name='Nome da hospedaria')),
                ('bedroom_id', models.PositiveIntegerField(verbose_name='ID Quarto')),
                ('bedroom_name', models.CharField(max_length=50, verbose_name='Nome do quarto')),
                ('start_date', models.DateField(verbose_name='Data de início')),
                ('end_date', models.DateField(verbose_name='Data do fim')),
            ],
        ),
    ]
