# Generated by Django 3.0.3 on 2020-03-09 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TravelEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_id', models.PositiveIntegerField(verbose_name='ID Agência')),
                ('agency_name', models.CharField(max_length=50, verbose_name='Nome da agência')),
                ('tour_id', models.PositiveIntegerField(verbose_name='ID Passeio')),
                ('tour_name', models.CharField(max_length=50, verbose_name='Nome do passeio')),
                ('date', models.DateField(verbose_name='Data do passeio')),
            ],
        ),
    ]
